# Generated by Django 5.1 on 2026-09-17 01:16

import apps.usuarios.models.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_corregir_rol_superusuarios'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', apps.usuarios.models.managers.UsuarioManager()),
            ],
        ),
    ]
