# Generated by Django 5.1 on 2026-08-25 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comisiones', '0001_initial'),
        ('personal', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='detalle_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='ventas.detalleventa'),
        ),
        migrations.AddField(
            model_name='comision',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='personal.empleado'),
        ),
        migrations.AddField(
            model_name='comision',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='ventas.venta'),
        ),
    ]
